### ISSUE TITLE
Add icon for Anki

### ISSUE THREAD

**Issue by k-kirill** [grungefox/AdwaitaX-icon-theme#1]
App website: https://apps.ankiweb.net/
Short description: Anki is a free and open-source flashcard program using spaced repetition, a technique from cognitive science for fast and long-lasting memorization. More details at [Anki Wikipedia page](https://en.wikipedia.org/wiki/Anki_(software))
Default icon: [Anki icon](https://en.wikipedia.org/wiki/Anki_(software)#/media/File:Anki-icon.svg)
Filename of Flatpak icon: `net.ankiweb.Anki`

**Comment by grungefox** [comment]
Done. Also thanks for all the information, this was very helpful. Hope you'll like it :))

**Comment by k-kirill** [comment]
> Done. Also thanks for all the information, this was very helpful. Hope you'll like it :))

I like the new icon. I appreciate your work and I am going to create more issues like this :) Thanks!
